services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5433:5432
    volumes:
      - .db/postgres-test:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=testing